// Mocks generated by Mockito 5.4.5 from annotations
// in v_starter_kits/test/use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:v_starter_kits/domain/domain.dart' as _i2;
import 'package:v_starter_kits/domain/src/entity_helper/pages.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SomethingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSomethingUseCase extends _i1.Mock implements _i2.SomethingUseCase {
  MockSomethingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i2.Failure, _i5.Pages<_i2.Something>>> getPage() =>
      (super.noSuchMethod(
            Invocation.method(#getPage, []),
            returnValue: _i3.Future<
              _i4.Either<_i2.Failure, _i5.Pages<_i2.Something>>
            >.value(
              _i6.dummyValue<_i4.Either<_i2.Failure, _i5.Pages<_i2.Something>>>(
                this,
                Invocation.method(#getPage, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i2.Failure, _i5.Pages<_i2.Something>>>);
}
